name: main-pipeline

on:
# workflow triggers when changes are pushed to remote branches specified
  push:
    branches: [main]

# workflow triggers when 'Run Workflow' button is used
  workflow_dispatch:
  
jobs:
  infra-pipeline:
    strategy:
      fail-fast: true
      max-parallel: 1
    uses: ./.github/workflows/build-test-deploy-infra.yaml
    secrets: inherit

